[package]
name = "griphook"
version = "0.1.0"
edition = "2024"
description = """
Griphook is a little tool to batch-rename a set of images.
It lets you view images in a folder, select some of them for renaming,
and transform their name by matching a regular expression.
"""
license = "MIT"
publish = false


[dependencies]
# Necessary for parsing of command line arguments
clap = { version = "4.6.6", features = ["derive"] }

# Necessary for the GUI
iced = { version = "0.14.0", features = ["image"] }

griphook_logic = { path = "../griphook_logic", default-features = false }

[features]
default = []
rsraw = ["griphook_logic/rsraw"]
perf = ["griphook_logic/perf"]