[package]
name = "griphook_logic"
version = "0.1.2"
edition = "2024"
description = """
Griphook is a little tool to batch-rename a set of images.
It lets you view images in a folder, select some of them for renaming,
and transform their name by matching a regular expression.

This is the library containing the program logic without the GUI.
"""
license = "MIT"
publish = false

[lib]
crate-type = ["lib"]


[dependencies]
# Necessary for file filtering and parsing
regex = { version = "1.13.1", default-features = false, features = ["std", "unicode"] }

# Necessary for working with images
image = { version = "0.25.10", default-features = false, features = ["jpeg", "bmp", "png", "tiff", "webp"] }

# Necessary for opening RAW image files
rsraw = { version = "0.1.1", optional = true }

[features]
default = []
rsraw = ["dep:rsraw"]
perf = ["regex/perf"]